<?php
/**
 * Created by PhpStorm.
 * User: pavka
 * Date: 10/15/15
 * Time: 6:28 PM
 */

namespace Energine\shop\components;


use Energine\share\components\Grid;
use Energine\share\gears\QAL;

class CountryEditor extends Grid{
    /**
     * @copydoc DBDataSet::__construct
     */
    public function __construct($name, array $params = NULL) {
        parent::__construct($name, $params); // TODO: Change the autogenerated stub
        $this->setTableName('site_country');
        $this->setOrder(['country_name' => QAL::ASC]);        
    }

    /**
     * @copydoc DBDataSet::createDataDescription
     */
    protected function createDataDescription() {
        $result = parent::createDataDescription(); // TODO: Change the autogenerated stub
        if($f = $result->getFieldDescriptionByName('country_tel_format')){
            $f->setProperty('pattern', '/^[0-9\.\- \(\)X]{10,16}$/');
            $f->setProperty('message', 'MSG_ERR_BAD_PLACEHOLDER');
        }
        return $result;
    }


}